import { renderPanel, renderBadge, renderMetric } from '../components/Library.js';

export interface DeliverPageConfig {
  isNoSession: boolean;
  selectedDestinationId?: string;
  selectedPreviewTab?: 'Markdown' | 'Excel' | 'Jira' | 'Azure DevOps' | 'JSON';
  readyToPublish?: boolean;
  readinessChecks?: { label: string; checked: boolean }[];
  deliverables?: { label: string; count: number }[];
  destinations?: { id: string; name: string; connected: boolean; status: string }[];
  namingTemplate?: string;
  versionConfig?: { version: string; baseline: string; build: string };
  partialPublish?: { label: string; checked: boolean }[];
  dryRun?: boolean;
  previewContent?: string;
  publishPlan?: string[];
  publishImpact?: { create: number; update: number; skip: number; warnings: number };
  validationRules?: { label: string; status: 'Passed' | 'Warning' | 'Failed' }[];
  timelineLogs?: string[];
}

export function renderDeliverPage(config: DeliverPageConfig): string {
  if (config.isNoSession) {
    return `
      <div style="animation: fade-in 0.2s ease-out; padding: 12px; text-align: center; color: var(--vscode-descriptionForeground);">
        <h3>Publish Workspace Empty</h3>
        <p style="font-size: 11px;">No active session loaded. Click on the 📄 <strong>Requirement</strong> sidebar icon to analyze a spec first.</p>
      </div>
    `;
  }

  // Active Publish Workspace Defaults
  const selectedDestinationId = config.selectedDestinationId || 'jira';
  const selectedPreviewTab = config.selectedPreviewTab || 'Markdown';
  const readyToPublish = config.readyToPublish ?? true;
  const namingTemplate = config.namingTemplate || '{project}_{story}_v{version}_{date}';
  const dryRun = config.dryRun ?? false;

  const versionConfig = config.versionConfig || { version: 'v2.3', baseline: 'Sprint 14', build: '127' };
  
  const readinessChecks = config.readinessChecks || [
    { label: 'Review Approved', checked: true },
    { label: 'Coverage Complete', checked: true },
    { label: 'Traceability Valid', checked: true },
    { label: 'No Critical Issues', checked: true }
  ];

  const deliverables = config.deliverables || [
    { label: 'Requirement spec', count: 1 },
    { label: 'Strategy plan', count: 1 },
    { label: 'Test cases', count: 42 },
    { label: 'Review report', count: 1 },
    { label: 'Traceability Matrix', count: 1 }
  ];

  const destinations = config.destinations || [
    { id: 'local', name: 'Local Excel / CSV', connected: true, status: 'Active' },
    { id: 'jira', name: 'Jira Software backlog', connected: true, status: 'Connected (PAY)' },
    { id: 'ado', name: 'Azure DevOps Boards', connected: true, status: 'Connected (POS)' },
    { id: 'zephyr', name: 'Zephyr Enterprise', connected: false, status: 'Disconnected' },
    { id: 'xray', name: 'Xray Jira Plugin', connected: false, status: 'Disconnected' },
    { id: 'pdf', name: 'PDF Delivery Report', connected: true, status: 'Ready' }
  ];

  const partialPublish = config.partialPublish || [
    { label: 'Test Cases', checked: true },
    { label: 'Review Logs', checked: true },
    { label: 'Strategy Objectives', checked: true },
    { label: 'Traceability Mapping', checked: true }
  ];

  const publishPlan = config.publishPlan || [
    'Create 42 Test Cases',
    'Update Jira User Story details',
    'Attach PDF Review Report',
    'Upload Traceability matrix'
  ];

  const publishImpact = config.publishImpact || { create: 42, update: 3, skip: 5, warnings: 2 };

  const validationRules = config.validationRules || [
    { label: 'File Names formatting', status: 'Passed' as const },
    { label: 'Required Fields checklist', status: 'Passed' as const },
    { label: 'Traceability Linkages', status: 'Passed' as const },
    { label: 'IDs sequences verification', status: 'Passed' as const },
    { label: 'Duplicate Keys bounds', status: 'Warning' as const }
  ];

  const timelineLogs = config.timelineLogs || [
    'Generated by AI engine',
    'Reviewed by QA team',
    'Approved by Lead',
    'Ready to Publish'
  ];

  const previewContent = config.previewContent || `# Webhook Verification Suite\n\n## TC-001: Stripe Webhook Clock-Drift Tolerances\n* Preconditions: HMAC keys configured.\n* Expected: processes signatures successfully.`;

  return `
    <div style="animation: fade-in 0.2s ease-out; font-size: 11px; display: flex; flex-direction: column; gap: 8px; box-sizing: border-box; width: 100%;">
      
      <!-- Summary Delivery Readiness Header Card -->
      <div style="background: var(--vscode-sideBarSectionHeader-background); border: 1px solid var(--vscode-panel-border); border-radius: 4px; padding: 10px; box-sizing: border-box; display: flex; flex-direction: column; gap: 8px; width: 100%;">
        <div style="display: flex; align-items: center; justify-content: space-between; flex-wrap: wrap;">
          <span style="font-size: 13px; font-weight: 700;">Publish & Delivery Center</span>
          <span style="color: var(--vscode-testing-iconPassedColor, #89D185); font-weight: bold; font-size: 10px;">
            Ready to Publish
          </span>
        </div>
        <div style="border-top: 1px solid var(--vscode-panel-border); padding-top: 6px; display: flex; flex-wrap: wrap; gap: 10px; color: var(--vscode-descriptionForeground);">
          ${readinessChecks.map(c => `<div>${c.checked ? '✓' : '⚠'} ${c.label}</div>`).join('')}
        </div>
      </div>

      <!-- Deliverables summary count card -->
      ${renderPanel('QA Deliverables Package Summary', `
        <div style="display: flex; flex-wrap: wrap; gap: 12px; align-items: center;">
          ${deliverables.map(d => `
            <div>
              <span style="color: var(--vscode-descriptionForeground); font-size: 9px;">${d.label}:</span>
              <strong style="color: var(--vscode-foreground); font-size: 11px;">${d.count}</strong>
            </div>
          `).join('')}
        </div>
      `)}

      <!-- Main Columns Flex Grid -->
      <div style="display: flex; flex-direction: column; gap: 8px;">

        <!-- Left Column: Destinations list & parameters configuration -->
        <div style="display: flex; flex-direction: column; gap: 8px; flex: 1;">
          
          <!-- Destinations list connections status indicators -->
          ${renderPanel('Target Destinations & Connections', `
            <div style="display: flex; flex-direction: column; gap: 4px;">
              ${destinations.map(dest => `
                <div onclick="postMessage({command: 'selectDestination', id: '${dest.id}'})" style="cursor: pointer; padding: 6px; border: 1px solid var(--vscode-panel-border); border-radius: 4px; display: flex; align-items: center; justify-content: space-between; background: ${dest.id === selectedDestinationId ? 'rgba(255,255,255,0.03)' : 'transparent'}; border-left: 2px solid ${dest.id === selectedDestinationId ? 'var(--vscode-button-background)' : 'transparent'};">
                  <span style="font-weight: 600;">${dest.name}</span>
                  <span style="font-size: 9px; color: ${dest.connected ? 'var(--vscode-testing-iconPassedColor, #89D185)' : 'var(--vscode-testing-iconFailedColor, #F48771)'};">
                    ${dest.status}
                  </span>
                </div>
              `).join('')}
            </div>
          `)}

          <!-- Version Configuration parameters -->
          ${renderPanel('Deliverable Version Configuration', `
            <div style="display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 4px;">
              <div style="display: flex; flex-direction: column; gap: 2px;">
                <span style="color: var(--vscode-descriptionForeground); font-size: 9px;">Version:</span>
                <input type="text" id="publish-ver" value="${versionConfig.version}" style="font-size: 10px; background: var(--vscode-input-background); color: var(--vscode-input-foreground); border: 1px solid var(--vscode-input-border); padding: 2px;" />
              </div>
              <div style="display: flex; flex-direction: column; gap: 2px;">
                <span style="color: var(--vscode-descriptionForeground); font-size: 9px;">Baseline:</span>
                <input type="text" id="publish-base" value="${versionConfig.baseline}" style="font-size: 10px; background: var(--vscode-input-background); color: var(--vscode-input-foreground); border: 1px solid var(--vscode-input-border); padding: 2px;" />
              </div>
              <div style="display: flex; flex-direction: column; gap: 2px;">
                <span style="color: var(--vscode-descriptionForeground); font-size: 9px;">Build:</span>
                <input type="text" id="publish-build" value="${versionConfig.build}" style="font-size: 10px; background: var(--vscode-input-background); color: var(--vscode-input-foreground); border: 1px solid var(--vscode-input-border); padding: 2px;" />
              </div>
            </div>
          `)}

          <!-- Naming Strategy templates -->
          ${renderPanel('Naming Rules Template spec', `
            <div style="display: flex; flex-direction: column; gap: 4px;">
              <span style="color: var(--vscode-descriptionForeground); font-size: 9px;">Naming Template pattern:</span>
              <input type="text" id="naming-strategy-input" value="${namingTemplate}" style="width: 100%; font-size: 10.5px; background: var(--vscode-input-background); color: var(--vscode-input-foreground); border: 1px solid var(--vscode-input-border); padding: 2px; box-sizing: border-box;" />
              <span style="font-size: 8px; opacity: 0.6;">Supports {project}, {story}, {version}, {date}, {sprint}.</span>
            </div>
          `)}

          <!-- Partial publishes checks -->
          ${renderPanel('Publish Scope items selection', `
            <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 6px;">
              ${partialPublish.map(p => `
                <div style="display: flex; align-items: center; gap: 4px;">
                  <input type="checkbox" ${p.checked ? 'checked' : ''} />
                  <span>${p.label}</span>
                </div>
              `).join('')}
            </div>
          `)}

          <!-- Dry Run checkbox -->
          <div style="display: flex; align-items: center; gap: 6px; padding: 4px;">
            <input type="checkbox" id="dry-run-check" ${dryRun ? 'checked' : ''} />
            <span style="font-weight: 700; color: var(--vscode-descriptionForeground);">Preview Changes only (Dry Run - Nothing uploaded)</span>
          </div>

        </div>

        <!-- Right Column: Previews, Validation Pre-Checks, Plans & Timelines -->
        <div style="display: flex; flex-direction: column; gap: 8px; flex: 1;">
          
          <!-- Live Preview tabs -->
          ${renderPanel('Compiled Deliverable Live Preview', `
            <div style="display: flex; gap: 4px; margin-bottom: 6px; border-bottom: 1px solid var(--vscode-panel-border); padding-bottom: 4px;">
              ${['Markdown', 'Excel', 'Jira', 'Azure DevOps', 'JSON']
                .map(
                  (tab) => `
                <button class="${tab === selectedPreviewTab ? 'btn-primary' : 'btn-secondary'}" onclick="postMessage({command: 'selectPreviewTab', tab: '${tab}'})" style="font-size: 8px; height: 16px; padding: 0 4px; line-height: 1; width: auto;">${tab}</button>
              `
                )
                .join('')}
            </div>
            <pre style="background: rgba(0,0,0,0.1); padding: 8px; border-radius: 4px; font-family: monospace; font-size: 9px; white-space: pre-wrap; margin: 0; box-sizing: border-box; width: 100%; max-height: 100px; overflow-y: auto;">${previewContent}</pre>
          `)}

          <!-- Export Validation Checklist -->
          ${renderPanel('Export Validation Checks Pre-Flight', `
            <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 4px; font-size: 9.5px;">
              ${validationRules.map(r => `
                <div style="display: flex; align-items: center; gap: 4px;">
                  <span style="color: ${r.status === 'Passed' ? 'var(--vscode-testing-iconPassedColor, #89D185)' : 'var(--vscode-testing-iconFailedColor, #F48771)'}; font-weight: bold;">
                    ${r.status === 'Passed' ? '✓' : '⚠'}
                  </span>
                  <span>${r.label}</span>
                </div>
              `).join('')}
            </div>
          `)}

          <!-- Publish Plan checklist -->
          ${renderPanel('Publish Plan schedule', `
            <div style="display: flex; flex-direction: column; gap: 3px; font-size: 9.5px;">
              ${publishPlan.map(task => `<div>• ${task}</div>`).join('')}
            </div>
          `)}

          <!-- Publish Impact details -->
          ${renderPanel('Publishing Impact Forecast', `
            <div style="display: flex; justify-content: space-between; align-items: center; font-size: 10px;">
              <div>Will Create: <strong style="color: var(--vscode-testing-iconPassedColor, #89D185);">${publishImpact.create}</strong></div>
              <div>Will Update: <strong style="color: var(--vscode-testing-iconQueuedColor, #CCA700);">${publishImpact.update}</strong></div>
              <div>Will Skip: <strong style="color: var(--vscode-descriptionForeground);">${publishImpact.skip}</strong></div>
              <div>Warnings: <strong style="color: var(--vscode-testing-iconFailedColor, #F48771);">${publishImpact.warnings}</strong></div>
            </div>
          `)}

          <!-- Sync history timeline logs -->
          ${renderPanel('Export Sync timeline logs', `
            <div style="font-family: monospace; font-size: 9px; line-height: 1.3;">
              ${timelineLogs
                .map(
                  (log, idx) => `
                <div>${idx + 1}. ${log} ${idx === timelineLogs.length - 1 ? '🟢' : '➔'}</div>
              `
                )
                .join('')}
            </div>
          `)}

          <!-- QA Delivery Report Handover PDF -->
          ${renderPanel('QA Delivery Summary Report PDF', `
            <div style="font-size: 9.5px; color: var(--vscode-descriptionForeground); margin-bottom: 6px;">
              Generate the official QA handover validation PDF containing requirement, strategy, review scorecard, and test results.
            </div>
            <button class="btn-secondary" onclick="postMessage({command: 'generatePDFSummary'})" style="font-size: 9px; height: 18px; padding: 0 6px; line-height: 1; width: 100%; box-sizing: border-box;">
              Generate Handover PDF Document
            </button>
          `)}

        </div>

      </div>

      <!-- Connections Configuration Toolbar -->
      <div style="background: var(--vscode-sideBarSectionHeader-background); border: 1px solid var(--vscode-panel-border); border-radius: 4px; padding: 8px; display: flex; gap: 4px; box-sizing: border-box; width: 100%;">
        <button class="qamate-toolbar-btn" onclick="postMessage({command: 'configureCredentials'})" style="flex: 1; padding: 4px; font-size: 9px; height: 22px; line-height: 1; background: var(--vscode-button-background); color: var(--vscode-button-foreground); border: 1px solid var(--vscode-panel-border); cursor: pointer; border-radius: 2px;">Connections Config</button>
        <button class="qamate-toolbar-btn" onclick="postMessage({command: 'runValidationCheck'})" style="flex: 1; padding: 4px; font-size: 9px; height: 22px; line-height: 1; background: var(--vscode-button-background); color: var(--vscode-button-foreground); border: 1px solid var(--vscode-panel-border); cursor: pointer; border-radius: 2px;">Validation Pre-Check</button>
        <button class="qamate-toolbar-btn" onclick="postMessage({command: 'reloadPreview'})" style="flex: 1; padding: 4px; font-size: 9px; height: 22px; line-height: 1; background: var(--vscode-button-background); color: var(--vscode-button-foreground); border: 1px solid var(--vscode-panel-border); cursor: pointer; border-radius: 2px;">Reload Preview</button>
      </div>

      <!-- Approve publish stepper buttons -->
      <div style="display: flex; flex-direction: column; gap: 4px; width: 100%;">
        <button class="btn-primary" onclick="postMessage({command: 'publishSuite', ver: document.getElementById('publish-ver').value, base: document.getElementById('publish-base').value, build: document.getElementById('publish-build').value, template: document.getElementById('naming-strategy-input').value, dryRun: document.getElementById('dry-run-check').checked})" style="height: 26px; line-height: 1; font-weight: bold; width: 100%; box-sizing: border-box;">
          Publish & Sync Suite ➔
        </button>
        <button class="btn-secondary" onclick="postMessage({command: 'switchTab', tab: 'dashboard'})" style="height: 22px; line-height: 1; font-weight: 600; width: 100%; box-sizing: border-box;">
          Back to Workspace Cockpit
        </button>
      </div>

    </div>
  `;
}
